[package]
name = "pest-bug-repr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1"
pest_derive = "2.1"
anyhow = "1.0"
rustyline = "6.2"
cfg-if = "0.1"
lazy_static = "1.0"